// <auto-generated />
using System;
using CrewRedTestAssessment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CrewRedTestAssessment.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260305184718_AddedIsDuplicated")]
    partial class AddedIsDuplicated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CrewRedTestAssessment.Models.Entities.Trip", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DOLocationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DropoffDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FareAmount")
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("ImportedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PULocationId")
                        .HasColumnType("integer");

                    b.Property<int>("PassengerCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PickupDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StoreAndFwdFlag")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("TipAmount")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("TripDistance")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("PULocationId")
                        .HasDatabaseName("ix_trip_pulocationid");

                    b.HasIndex("TripDistance")
                        .HasDatabaseName("ix_trip_tripdistance");

                    b.HasIndex("PULocationId", "TipAmount")
                        .HasDatabaseName("ix_trip_pulocationid_tipamount");

                    b.HasIndex("PULocationId", "TripDistance")
                        .HasDatabaseName("ix_trip_pulocationid_tripdistance");

                    b.HasIndex("PickupDateTime", "DropoffDateTime", "PassengerCount")
                        .HasDatabaseName("ix_trip_duplicate_detection");

                    b.ToTable("Trips", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
